# Generated by Django 3.2.4 on 2021-07-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiSahayak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopupload',
            name='productpic',
            field=models.ImageField(upload_to=''),
        ),
    ]
