# Generated by Django 3.2.4 on 2021-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiSahayak', '0002_alter_shopupload_productpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopupload',
            name='productpic',
            field=models.ImageField(upload_to='media/uploads'),
        ),
    ]
