# Generated by Django 3.2.4 on 2021-07-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiSahayak', '0005_alter_foodorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
