# Generated by Django 3.2.4 on 2021-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiSahayak', '0006_alter_foodorder_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cfirstname', models.CharField(max_length=50)),
                ('Clastname', models.CharField(max_length=50)),
                ('Ccountry', models.CharField(max_length=50)),
                ('Cstate', models.CharField(max_length=50)),
                ('Ccity', models.CharField(max_length=50)),
                ('Caddress', models.CharField(max_length=300)),
                ('Cpin', models.CharField(max_length=30)),
                ('Cphone', models.CharField(max_length=10)),
                ('Cproductname', models.CharField(max_length=50)),
                ('CproductID', models.CharField(max_length=20)),
                ('Cquantity', models.PositiveIntegerField()),
                ('Cmsg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerproducttype', models.CharField(max_length=50)),
                ('farmerproductname', models.CharField(max_length=50)),
                ('IDproductfarmer', models.CharField(max_length=20)),
                ('pricefarmer', models.CharField(max_length=10)),
                ('descfarmer', models.CharField(max_length=500)),
                ('farmername', models.CharField(max_length=50)),
                ('farmerlocation', models.CharField(max_length=100)),
                ('farmercontact', models.CharField(max_length=10)),
                ('postdatefarmer', models.DateTimeField()),
            ],
        ),
    ]
