# Generated by Django 3.2.4 on 2021-11-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiSahayak', '0007_customerorder_farmerupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopupload',
            name='productpic',
        ),
    ]
